CREATE TABLE TB_STORY(
    STORY_NO	NUMBER NOT NULL,
    STORY_TITLE	VARCHAR2(150),
    STORY_CN	VARCHAR2(3000),
    STORY_DATE	DATE,
    STORY_FROM	VARCHAR2(2000),
    STATUS	CHAR(1 BYTE)
);

CREATE SEQUENCE SEQ_ST;